[package]
name = "clib"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
figlet-rs = "0.1.5"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
scraper = "0.23.1"
